version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8001:8000"
    volumes:
      - ./backend/main.py:/app/main.py
      - ./backend/bot_heuristics.py:/app/bot_heuristics.py
      - ./backend/game.py:/app/game.py
      - ./frontend/dist:/app/dist
    environment:
      - PYTHONUNBUFFERED=1
